//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use super::sea_orm_active_enums::Genderenum;
use super::sea_orm_active_enums::Namestyleenum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "baby_name")]
pub struct Model {
    pub name: String,
    pub gender: Genderenum,
    pub style: Namestyleenum,
    pub meaning: Option<String>,
    pub pinyin: Option<String>,
    pub stroke_count: Option<i32>,
    pub is_lucky: Option<bool>,
    pub popularity: i32,
    pub tags: Option<String>,
    pub source: Option<String>,
    pub is_active: Option<bool>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
