//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15
//!
//! 本模块实体所需枚举(自集中 entities crate 下沉至各模块, 仅保留本模块子集)。

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "genderenum")]
pub enum Genderenum {
    #[sea_orm(string_value = "BOY")]
    Boy,
    #[sea_orm(string_value = "GIRL")]
    Girl,
    #[sea_orm(string_value = "UNKNOWN")]
    Unknown,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "namestyleenum")]
pub enum Namestyleenum {
    #[sea_orm(string_value = "TRADITIONAL")]
    Traditional,
    #[sea_orm(string_value = "MODERN")]
    Modern,
    #[sea_orm(string_value = "LITERARY")]
    Literary,
    #[sea_orm(string_value = "SIMPLE")]
    Simple,
    #[sea_orm(string_value = "UNIQUE")]
    Unique,
}
