//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "project_document")]
pub struct Model {
    pub project_id: String,
    pub name: String,
    pub file_extension: String,
    pub mime_type: Option<String>,
    pub file_size_bytes: i32,
    pub physical_path: String,
    pub description: Option<String>,
    pub parse_status: String,
    pub chunk_count: i32,
    pub error_message: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub uploaded_by: String,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary")]
    pub parse_steps: Json,
    pub content_hash: Option<String>,
    pub entry_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
