//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15
//!
//! 补充 belongs_to 关系: 联 user 表(count_admins/关键词过滤)与 project 表(我参与的项目)。

use crate::do_::entity::project;
use module_authorization::do_::entity::user;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "project_member")]
pub struct Model {
    pub user_id: String,
    pub project_id: String,
    pub role: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// 直连用户(联 user 表校验在职状态/账号昵称)
    #[sea_orm(
        belongs_to = "user::Entity",
        from = "Column::UserId",
        to = "user::Column::Id"
    )]
    User,
    /// 所属项目(我参与的项目联查)
    #[sea_orm(
        belongs_to = "project::Entity",
        from = "Column::ProjectId",
        to = "project::Column::Id"
    )]
    Project,
}

impl Related<user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
