//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15
//!
//! 补充 belongs_to 关系: 联 dept 表(部门名展示)与 project 表(按项目级联删除)。

use crate::do_::entity::project;
use module_authorization::do_::entity::dept;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "project_dept")]
pub struct Model {
    pub project_id: String,
    pub dept_id: String,
    pub role: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// 授权部门(联 dept 表取部门名)
    #[sea_orm(
        belongs_to = "dept::Entity",
        from = "Column::DeptId",
        to = "dept::Column::Id"
    )]
    Dept,
    /// 所属项目
    #[sea_orm(
        belongs_to = "project::Entity",
        from = "Column::ProjectId",
        to = "project::Column::Id"
    )]
    Project,
}

impl Related<dept::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dept.def()
    }
}

impl Related<project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
