//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15
//!
//! 本模块实体所需枚举(自集中 entities crate 下沉至各模块, 仅保留本模块子集)。
//!
//! 对齐说明: chat_message.role 与 Python module_ai.utils.llm.types.RoleType
//! (str Enum, 值为小写 system/user/assistant)共用同一数据库列, 故 string_value
//! 与 serde 序列化均采用小写, 保证跨语言数据互通。

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "roletype")]
#[serde(rename_all = "lowercase")]
pub enum Roletype {
    #[sea_orm(string_value = "system")]
    System,
    #[sea_orm(string_value = "user")]
    User,
    #[sea_orm(string_value = "assistant")]
    Assistant,
}

impl Roletype {
    /// 数据库/序列化口径的小写字符串(对齐 Python RoleType 枚举值)
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::System => "system",
            Self::User => "user",
            Self::Assistant => "assistant",
        }
    }
}
