//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user_model")]
pub struct Model {
    pub user_id: String,
    pub chat_model_id: Option<String>,
    pub embedding_model_id: Option<String>,
    pub rerank_model_id: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: DateTimeWithTimeZone,
    pub fallback_disabled: bool,
    pub asr_model_id: Option<String>,
    pub tts_model_id: Option<String>,
    pub vad_model_id: Option<String>,
    pub denoise_model_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
