//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "model_config")]
pub struct Model {
    pub model_type: String,
    pub server_type: String,
    pub model: String,
    pub url: Option<String>,
    pub api_key: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub pay_in: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub pay_out: Option<f64>,
    pub input_tokens: Option<i32>,
    pub out_tokens: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub temperature: Option<f64>,
    pub timeout: Option<i32>,
    pub no_think: Option<bool>,
    pub extra: Option<Json>,
    pub user_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: DateTimeWithTimeZone,
    pub is_public: bool,
    pub scope: String,
    pub dept_id: Option<String>,
    pub is_default: bool,
    pub display_name: Option<String>,
    pub is_active: bool,
    pub check_valid: Option<bool>,
    pub check_format: Option<bool>,
    pub checked_at: Option<DateTimeWithTimeZone>,
    pub check_result: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
