//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "geo_feature")]
pub struct Model {
    pub name: String,
    pub feature_type: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub properties: Option<Json>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub user_id: String,
    /// 几何体列: Rust 侧无 PostGIS, 以 WKT 文本存储(对齐 Python PostGIS geometry 列的存储语义)
    #[sea_orm(column_type = "Text")]
    pub geometry: String,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub style: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
