[package]
name = "module-task"
version.workspace = true
edition.workspace = true

[dependencies]
# 公共包(错误/分页/动态配置/表注册中心)
common = { workspace = true }
# 鉴权依赖(AuthUserId/authorize/权限注册) —— 依赖方向: 本模块 → module-authorization
module-authorization = { workspace = true }

axum = { workspace = true }
tokio = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
