//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "permission")]
pub struct Model {
    pub parent_id: Option<String>,
    pub name: String,
    pub code: String,
    pub description: Option<String>,
    pub menu_type: String,
    pub path: Option<String>,
    pub component: Option<String>,
    pub perms: Option<String>,
    pub icon: Option<String>,
    pub order_num: i32,
    pub visible: bool,
    pub is_active: bool,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
