//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15
//!
//! 本模块实体所需枚举(自集中 entities crate 下沉至各模块, 仅保留本模块子集)。

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "tokentype")]
pub enum Tokentype {
    #[sea_orm(string_value = "access")]
    Access,
    #[sea_orm(string_value = "refresh")]
    Refresh,
}
