//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "agent")]
pub struct Model {
    pub name: String,
    pub description: String,
    pub system_prompt: String,
    pub is_public: bool,
    pub is_builtin: bool,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub created_by: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: DateTimeWithTimeZone,
    pub input_type: String,
    pub output_type: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub input_schema: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub output_schema: Option<Json>,
    pub agent_type: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub workflow: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
