//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "checkpoint_blobs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub thread_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub checkpoint_ns: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub channel: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub version: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub blob: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
