//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use super::sea_orm_active_enums::Storagetype;
use super::sea_orm_active_enums::Taskstatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "file_content")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub content_hash: String,
    pub physical_storage: Option<String>,
    pub file_size_bytes: Option<i32>,
    pub ref_count: i32,
    pub storage_type: Option<Storagetype>,
    pub content_status: Option<Taskstatus>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
