//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use super::sea_orm_active_enums::Taskstatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "file_entry")]
pub struct Model {
    pub pid: Option<String>,
    pub name: String,
    pub logical_path: String,
    pub is_directory: bool,
    pub content_hash: Option<String>,
    pub file_size_bytes: Option<i32>,
    pub file_extension: Option<String>,
    pub mime_type: Option<String>,
    pub description: Option<String>,
    pub is_active: bool,
    pub user_id: Option<String>,
    pub group_id: Option<String>,
    pub entry_status: Option<Taskstatus>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: DateTimeWithTimeZone,
    pub source_module: Option<String>,
    pub tags: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
