//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15
//!
//! 本模块实体所需枚举(自集中 entities crate 下沉至各模块, 仅保留本模块子集)。

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "storagetype")]
pub enum Storagetype {
    #[sea_orm(string_value = "LOCAL")]
    Local,
    #[sea_orm(string_value = "S3")]
    S3,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "taskstatus")]
pub enum Taskstatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "RUNNING")]
    Running,
    #[sea_orm(string_value = "PAUSED")]
    Paused,
    #[sea_orm(string_value = "SUCCESS")]
    Success,
    #[sea_orm(string_value = "FAILED")]
    Failed,
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
    #[sea_orm(string_value = "EXPIRED")]
    Expired,
}
