/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/_server': RouteRecordInfo<'/_server', '/_server', Record<never, never>, Record<never, never>, '/_server/' | '/_server/database/overview' | '/_server/database/template'>,
    '/_server/': RouteRecordInfo<'/_server/', '/_server', Record<never, never>, Record<never, never>>,
    '/_server/database/overview': RouteRecordInfo<'/_server/database/overview', '/_server/database/overview', Record<never, never>, Record<never, never>>,
    '/_server/database/template': RouteRecordInfo<'/_server/database/template', '/_server/database/template', Record<never, never>, Record<never, never>>,
    '/[..all]': RouteRecordInfo<'/[..all]', '/:ll(.*)', { ll: ParamValue<true> }, { ll: ParamValue<false> }>,
    '/AboutView': RouteRecordInfo<'/AboutView', '/AboutView', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/_server.vue': {
      routes: '/_server' | '/_server/' | '/_server/database' | '/_server/database/overview' | '/_server/database/template'
      views: 'default'
    }
    'src/pages/_server/index.vue': {
      routes: '/_server/'
      views: never
    }
    'src/pages/_server/database/overview.vue': {
      routes: '/_server/database/overview'
      views: never
    }
    'src/pages/_server/database/template.vue': {
      routes: '/_server/database/template'
      views: never
    }
    'src/pages/[..all].vue': {
      routes: '/[..all]'
      views: never
    }
    'src/pages/AboutView.vue': {
      routes: '/AboutView'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
