/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/_sys': RouteRecordInfo<'/_sys', '/_sys', Record<never, never>, Record<never, never>, '/_sys/' | '/_sys/ai/chat' | '/_sys/ai/ocr' | '/_sys/database/model_config' | '/_sys/database/overview' | '/_sys/database/todolist' | '/_sys/database/user' | '/_sys/manager/user' | '/_sys/monitor/uistore' | '/_sys/template/container' | '/_sys/template/infoview' | '/_sys/template/overview' | '/_sys/template/template'>,
    '/_sys/': RouteRecordInfo<'/_sys/', '/_sys', Record<never, never>, Record<never, never>>,
    '/_sys/ai/chat': RouteRecordInfo<'/_sys/ai/chat', '/_sys/ai/chat', Record<never, never>, Record<never, never>>,
    '/_sys/ai/ocr': RouteRecordInfo<'/_sys/ai/ocr', '/_sys/ai/ocr', Record<never, never>, Record<never, never>>,
    '/_sys/database/model_config': RouteRecordInfo<'/_sys/database/model_config', '/_sys/database/model_config', Record<never, never>, Record<never, never>>,
    '/_sys/database/overview': RouteRecordInfo<'/_sys/database/overview', '/_sys/database/overview', Record<never, never>, Record<never, never>>,
    '/_sys/database/todolist': RouteRecordInfo<'/_sys/database/todolist', '/_sys/database/todolist', Record<never, never>, Record<never, never>>,
    '/_sys/database/user': RouteRecordInfo<'/_sys/database/user', '/_sys/database/user', Record<never, never>, Record<never, never>>,
    '/_sys/manager/user': RouteRecordInfo<'/_sys/manager/user', '/_sys/manager/user', Record<never, never>, Record<never, never>>,
    '/_sys/monitor/uistore': RouteRecordInfo<'/_sys/monitor/uistore', '/_sys/monitor/uistore', Record<never, never>, Record<never, never>>,
    '/_sys/template/container': RouteRecordInfo<'/_sys/template/container', '/_sys/template/container', Record<never, never>, Record<never, never>>,
    '/_sys/template/infoview': RouteRecordInfo<'/_sys/template/infoview', '/_sys/template/infoview', Record<never, never>, Record<never, never>>,
    '/_sys/template/overview': RouteRecordInfo<'/_sys/template/overview', '/_sys/template/overview', Record<never, never>, Record<never, never>>,
    '/_sys/template/template': RouteRecordInfo<'/_sys/template/template', '/_sys/template/template', Record<never, never>, Record<never, never>>,
    '/[..all]': RouteRecordInfo<'/[..all]', '/:ll(.*)', { ll: ParamValue<true> }, { ll: ParamValue<false> }>,
    '/AboutView': RouteRecordInfo<'/AboutView', '/AboutView', Record<never, never>, Record<never, never>>,
    '/setting': RouteRecordInfo<'/setting', '/setting', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/_sys.vue': {
      routes: '/_sys' | '/_sys/' | '/_sys/ai' | '/_sys/ai/chat' | '/_sys/template/container' | '/_sys/database' | '/_sys/template/infoview' | '/_sys/manager' | '/_sys/database/model_config' | '/_sys/monitor' | '/_sys/ai/ocr' | '/_sys/database/overview' | '/_sys/template/overview' | '/_sys/template' | '/_sys/template/template' | '/_sys/database/todolist' | '/_sys/monitor/uistore' | '/_sys/manager/user' | '/_sys/database/user'
      views: 'default'
    }
    'src/pages/_sys/index.vue': {
      routes: '/_sys/'
      views: never
    }
    'src/pages/_sys/ai/chat.vue': {
      routes: '/_sys/ai/chat'
      views: never
    }
    'src/pages/_sys/ai/ocr.vue': {
      routes: '/_sys/ai/ocr'
      views: never
    }
    'src/pages/_sys/database/model_config.vue': {
      routes: '/_sys/database/model_config'
      views: never
    }
    'src/pages/_sys/database/overview.vue': {
      routes: '/_sys/database/overview'
      views: never
    }
    'src/pages/_sys/database/todolist.vue': {
      routes: '/_sys/database/todolist'
      views: never
    }
    'src/pages/_sys/database/user.vue': {
      routes: '/_sys/database/user'
      views: never
    }
    'src/pages/_sys/manager/user.vue': {
      routes: '/_sys/manager/user'
      views: never
    }
    'src/pages/_sys/monitor/uistore.vue': {
      routes: '/_sys/monitor/uistore'
      views: never
    }
    'src/pages/_sys/template/container.vue': {
      routes: '/_sys/template/container'
      views: never
    }
    'src/pages/_sys/template/infoview.vue': {
      routes: '/_sys/template/infoview'
      views: never
    }
    'src/pages/_sys/template/overview.vue': {
      routes: '/_sys/template/overview'
      views: never
    }
    'src/pages/_sys/template/template.vue': {
      routes: '/_sys/template/template'
      views: never
    }
    'src/pages/[..all].vue': {
      routes: '/[..all]'
      views: never
    }
    'src/pages/AboutView.vue': {
      routes: '/AboutView'
      views: never
    }
    'src/pages/setting.vue': {
      routes: '/setting'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
