/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[..all]': RouteRecordInfo<'/[..all]', '/:ll(.*)', { ll: ParamValue<true> }, { ll: ParamValue<false> }>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/ai/chat': RouteRecordInfo<'/ai/chat', '/ai/chat', Record<never, never>, Record<never, never>>,
    '/ai/model_config': RouteRecordInfo<'/ai/model_config', '/ai/model_config', Record<never, never>, Record<never, never>>,
    '/ai/ocr': RouteRecordInfo<'/ai/ocr', '/ai/ocr', Record<never, never>, Record<never, never>>,
    '/ai/voice': RouteRecordInfo<'/ai/voice', '/ai/voice', Record<never, never>, Record<never, never>>,
    '/authorization/casbin': RouteRecordInfo<'/authorization/casbin', '/authorization/casbin', Record<never, never>, Record<never, never>>,
    '/authorization/dept': RouteRecordInfo<'/authorization/dept', '/authorization/dept', Record<never, never>, Record<never, never>>,
    '/authorization/permission': RouteRecordInfo<'/authorization/permission', '/authorization/permission', Record<never, never>, Record<never, never>>,
    '/authorization/role': RouteRecordInfo<'/authorization/role', '/authorization/role', Record<never, never>, Record<never, never>>,
    '/authorization/user': RouteRecordInfo<'/authorization/user', '/authorization/user', Record<never, never>, Record<never, never>>,
    '/file/': RouteRecordInfo<'/file/', '/file', Record<never, never>, Record<never, never>>,
    '/geometry/earth': RouteRecordInfo<'/geometry/earth', '/geometry/earth', Record<never, never>, Record<never, never>>,
    '/life/baby_name': RouteRecordInfo<'/life/baby_name', '/life/baby_name', Record<never, never>, Record<never, never>>,
    '/little_utils/todolist': RouteRecordInfo<'/little_utils/todolist', '/little_utils/todolist', Record<never, never>, Record<never, never>>,
    '/main/dict': RouteRecordInfo<'/main/dict', '/main/dict', Record<never, never>, Record<never, never>>,
    '/main/overview': RouteRecordInfo<'/main/overview', '/main/overview', Record<never, never>, Record<never, never>>,
    '/monitor/server_status': RouteRecordInfo<'/monitor/server_status', '/monitor/server_status', Record<never, never>, Record<never, never>>,
    '/monitor/uistore': RouteRecordInfo<'/monitor/uistore', '/monitor/uistore', Record<never, never>, Record<never, never>>,
    '/rag/conversation': RouteRecordInfo<'/rag/conversation', '/rag/conversation', Record<never, never>, Record<never, never>>,
    '/rag/document': RouteRecordInfo<'/rag/document', '/rag/document', Record<never, never>, Record<never, never>>,
    '/rag/member': RouteRecordInfo<'/rag/member', '/rag/member', Record<never, never>, Record<never, never>>,
    '/rag/project': RouteRecordInfo<'/rag/project', '/rag/project', Record<never, never>, Record<never, never>>,
    '/setting': RouteRecordInfo<'/setting', '/setting', Record<never, never>, Record<never, never>>,
    '/task/queue': RouteRecordInfo<'/task/queue', '/task/queue', Record<never, never>, Record<never, never>>,
    '/template/babylon': RouteRecordInfo<'/template/babylon', '/template/babylon', Record<never, never>, Record<never, never>>,
    '/template/container': RouteRecordInfo<'/template/container', '/template/container', Record<never, never>, Record<never, never>>,
    '/template/infoview': RouteRecordInfo<'/template/infoview', '/template/infoview', Record<never, never>, Record<never, never>>,
    '/template/mediapipe_face': RouteRecordInfo<'/template/mediapipe_face', '/template/mediapipe_face', Record<never, never>, Record<never, never>>,
    '/template/overview': RouteRecordInfo<'/template/overview', '/template/overview', Record<never, never>, Record<never, never>>,
    '/template/template': RouteRecordInfo<'/template/template', '/template/template', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[..all].vue': {
      routes: '/[..all]'
      views: never
    }
    'src/pages/admin.vue': {
      routes: '/admin'
      views: never
    }
    'src/modules/ai/pages/chat.vue': {
      routes: '/ai/chat'
      views: never
    }
    'src/modules/ai/pages/model_config.vue': {
      routes: '/ai/model_config'
      views: never
    }
    'src/modules/ai/pages/ocr.vue': {
      routes: '/ai/ocr'
      views: never
    }
    'src/modules/ai/pages/voice.vue': {
      routes: '/ai/voice'
      views: never
    }
    'src/modules/authorization/pages/casbin.vue': {
      routes: '/authorization/casbin'
      views: never
    }
    'src/modules/authorization/pages/dept.vue': {
      routes: '/authorization/dept'
      views: never
    }
    'src/modules/authorization/pages/permission.vue': {
      routes: '/authorization/permission'
      views: never
    }
    'src/modules/authorization/pages/role.vue': {
      routes: '/authorization/role'
      views: never
    }
    'src/modules/authorization/pages/user.vue': {
      routes: '/authorization/user'
      views: never
    }
    'src/modules/file/pages/index.vue': {
      routes: '/file/'
      views: never
    }
    'src/modules/geometry/pages/earth.vue': {
      routes: '/geometry/earth'
      views: never
    }
    'src/modules/life/pages/baby_name.vue': {
      routes: '/life/baby_name'
      views: never
    }
    'src/modules/little_utils/pages/todolist.vue': {
      routes: '/little_utils/todolist'
      views: never
    }
    'src/modules/main/pages/dict.vue': {
      routes: '/main/dict'
      views: never
    }
    'src/modules/main/pages/overview.vue': {
      routes: '/main/overview'
      views: never
    }
    'src/modules/monitor/pages/server_status.vue': {
      routes: '/monitor/server_status'
      views: never
    }
    'src/modules/monitor/pages/uistore.vue': {
      routes: '/monitor/uistore'
      views: never
    }
    'src/modules/rag/pages/conversation.vue': {
      routes: '/rag/conversation'
      views: never
    }
    'src/modules/rag/pages/document.vue': {
      routes: '/rag/document'
      views: never
    }
    'src/modules/rag/pages/member.vue': {
      routes: '/rag/member'
      views: never
    }
    'src/modules/rag/pages/project.vue': {
      routes: '/rag/project'
      views: never
    }
    'src/pages/setting.vue': {
      routes: '/setting'
      views: never
    }
    'src/modules/task/pages/queue.vue': {
      routes: '/task/queue'
      views: never
    }
    'src/modules/template/pages/babylon.vue': {
      routes: '/template/babylon'
      views: never
    }
    'src/modules/template/pages/container.vue': {
      routes: '/template/container'
      views: never
    }
    'src/modules/template/pages/infoview.vue': {
      routes: '/template/infoview'
      views: never
    }
    'src/modules/template/pages/mediapipe_face.vue': {
      routes: '/template/mediapipe_face'
      views: never
    }
    'src/modules/template/pages/overview.vue': {
      routes: '/template/overview'
      views: never
    }
    'src/modules/template/pages/template.vue': {
      routes: '/template/template'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
